// source: yamcs/api/annotations.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var google_protobuf_descriptor_pb = require('google-protobuf/google/protobuf/descriptor_pb.js');
goog.object.extend(proto, google_protobuf_descriptor_pb);
goog.exportSymbol('proto.yamcs.api.FieldBehavior', null, global);
goog.exportSymbol('proto.yamcs.api.HttpRoute', null, global);
goog.exportSymbol('proto.yamcs.api.HttpRoute.PatternCase', null, global);
goog.exportSymbol('proto.yamcs.api.WebSocketTopic', null, global);
goog.exportSymbol('proto.yamcs.api.fieldBehaviorList', null, global);
goog.exportSymbol('proto.yamcs.api.label', null, global);
goog.exportSymbol('proto.yamcs.api.route', null, global);
goog.exportSymbol('proto.yamcs.api.websocket', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yamcs.api.HttpRoute = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.yamcs.api.HttpRoute.repeatedFields_, proto.yamcs.api.HttpRoute.oneofGroups_);
};
goog.inherits(proto.yamcs.api.HttpRoute, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yamcs.api.HttpRoute.displayName = 'proto.yamcs.api.HttpRoute';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yamcs.api.WebSocketTopic = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.yamcs.api.WebSocketTopic.repeatedFields_, null);
};
goog.inherits(proto.yamcs.api.WebSocketTopic, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yamcs.api.WebSocketTopic.displayName = 'proto.yamcs.api.WebSocketTopic';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.yamcs.api.HttpRoute.repeatedFields_ = [11];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.yamcs.api.HttpRoute.oneofGroups_ = [[1,2,3,4,5]];

/**
 * @enum {number}
 */
proto.yamcs.api.HttpRoute.PatternCase = {
  PATTERN_NOT_SET: 0,
  GET: 1,
  PUT: 2,
  POST: 3,
  DELETE: 4,
  PATCH: 5
};

/**
 * @return {proto.yamcs.api.HttpRoute.PatternCase}
 */
proto.yamcs.api.HttpRoute.prototype.getPatternCase = function() {
  return /** @type {proto.yamcs.api.HttpRoute.PatternCase} */(jspb.Message.computeOneofCase(this, proto.yamcs.api.HttpRoute.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yamcs.api.HttpRoute.prototype.toObject = function(opt_includeInstance) {
  return proto.yamcs.api.HttpRoute.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yamcs.api.HttpRoute} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.api.HttpRoute.toObject = function(includeInstance, msg) {
  var f, obj = {
    get: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    put: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    post: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    pb_delete: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
    patch: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f,
    deprecated: (f = jspb.Message.getBooleanField(msg, 6)) == null ? undefined : f,
    body: (f = jspb.Message.getField(msg, 7)) == null ? undefined : f,
    maxBodySize: (f = jspb.Message.getField(msg, 8)) == null ? undefined : f,
    offloaded: (f = jspb.Message.getBooleanField(msg, 9)) == null ? undefined : f,
    fieldMaskRoot: (f = jspb.Message.getField(msg, 10)) == null ? undefined : f,
    additionalBindingsList: jspb.Message.toObjectList(msg.getAdditionalBindingsList(),
    proto.yamcs.api.HttpRoute.toObject, includeInstance),
    log: (f = jspb.Message.getField(msg, 12)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yamcs.api.HttpRoute}
 */
proto.yamcs.api.HttpRoute.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yamcs.api.HttpRoute;
  return proto.yamcs.api.HttpRoute.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yamcs.api.HttpRoute} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yamcs.api.HttpRoute}
 */
proto.yamcs.api.HttpRoute.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setGet(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPut(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPost(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDelete(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPatch(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDeprecated(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setBody(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxBodySize(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setOffloaded(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setFieldMaskRoot(value);
      break;
    case 11:
      var value = new proto.yamcs.api.HttpRoute;
      reader.readMessage(value,proto.yamcs.api.HttpRoute.deserializeBinaryFromReader);
      msg.addAdditionalBindings(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setLog(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yamcs.api.HttpRoute.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yamcs.api.HttpRoute.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yamcs.api.HttpRoute} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.api.HttpRoute.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeBool(
      6,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeString(
      7,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeBool(
      9,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getAdditionalBindingsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      proto.yamcs.api.HttpRoute.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 12));
  if (f != null) {
    writer.writeString(
      12,
      f
    );
  }
};


/**
 * optional string get = 1;
 * @return {string}
 */
proto.yamcs.api.HttpRoute.prototype.getGet = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.api.HttpRoute} returns this
 */
proto.yamcs.api.HttpRoute.prototype.setGet = function(value) {
  return jspb.Message.setOneofField(this, 1, proto.yamcs.api.HttpRoute.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.api.HttpRoute} returns this
 */
proto.yamcs.api.HttpRoute.prototype.clearGet = function() {
  return jspb.Message.setOneofField(this, 1, proto.yamcs.api.HttpRoute.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.api.HttpRoute.prototype.hasGet = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string put = 2;
 * @return {string}
 */
proto.yamcs.api.HttpRoute.prototype.getPut = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.api.HttpRoute} returns this
 */
proto.yamcs.api.HttpRoute.prototype.setPut = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.yamcs.api.HttpRoute.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.api.HttpRoute} returns this
 */
proto.yamcs.api.HttpRoute.prototype.clearPut = function() {
  return jspb.Message.setOneofField(this, 2, proto.yamcs.api.HttpRoute.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.api.HttpRoute.prototype.hasPut = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string post = 3;
 * @return {string}
 */
proto.yamcs.api.HttpRoute.prototype.getPost = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.api.HttpRoute} returns this
 */
proto.yamcs.api.HttpRoute.prototype.setPost = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.yamcs.api.HttpRoute.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.api.HttpRoute} returns this
 */
proto.yamcs.api.HttpRoute.prototype.clearPost = function() {
  return jspb.Message.setOneofField(this, 3, proto.yamcs.api.HttpRoute.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.api.HttpRoute.prototype.hasPost = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string delete = 4;
 * @return {string}
 */
proto.yamcs.api.HttpRoute.prototype.getDelete = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.api.HttpRoute} returns this
 */
proto.yamcs.api.HttpRoute.prototype.setDelete = function(value) {
  return jspb.Message.setOneofField(this, 4, proto.yamcs.api.HttpRoute.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.api.HttpRoute} returns this
 */
proto.yamcs.api.HttpRoute.prototype.clearDelete = function() {
  return jspb.Message.setOneofField(this, 4, proto.yamcs.api.HttpRoute.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.api.HttpRoute.prototype.hasDelete = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string patch = 5;
 * @return {string}
 */
proto.yamcs.api.HttpRoute.prototype.getPatch = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.api.HttpRoute} returns this
 */
proto.yamcs.api.HttpRoute.prototype.setPatch = function(value) {
  return jspb.Message.setOneofField(this, 5, proto.yamcs.api.HttpRoute.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.api.HttpRoute} returns this
 */
proto.yamcs.api.HttpRoute.prototype.clearPatch = function() {
  return jspb.Message.setOneofField(this, 5, proto.yamcs.api.HttpRoute.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.api.HttpRoute.prototype.hasPatch = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional bool deprecated = 6;
 * @return {boolean}
 */
proto.yamcs.api.HttpRoute.prototype.getDeprecated = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.yamcs.api.HttpRoute} returns this
 */
proto.yamcs.api.HttpRoute.prototype.setDeprecated = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.api.HttpRoute} returns this
 */
proto.yamcs.api.HttpRoute.prototype.clearDeprecated = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.api.HttpRoute.prototype.hasDeprecated = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string body = 7;
 * @return {string}
 */
proto.yamcs.api.HttpRoute.prototype.getBody = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.api.HttpRoute} returns this
 */
proto.yamcs.api.HttpRoute.prototype.setBody = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.api.HttpRoute} returns this
 */
proto.yamcs.api.HttpRoute.prototype.clearBody = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.api.HttpRoute.prototype.hasBody = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional int32 max_body_size = 8;
 * @return {number}
 */
proto.yamcs.api.HttpRoute.prototype.getMaxBodySize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.yamcs.api.HttpRoute} returns this
 */
proto.yamcs.api.HttpRoute.prototype.setMaxBodySize = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.api.HttpRoute} returns this
 */
proto.yamcs.api.HttpRoute.prototype.clearMaxBodySize = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.api.HttpRoute.prototype.hasMaxBodySize = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional bool offloaded = 9;
 * @return {boolean}
 */
proto.yamcs.api.HttpRoute.prototype.getOffloaded = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.yamcs.api.HttpRoute} returns this
 */
proto.yamcs.api.HttpRoute.prototype.setOffloaded = function(value) {
  return jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.api.HttpRoute} returns this
 */
proto.yamcs.api.HttpRoute.prototype.clearOffloaded = function() {
  return jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.api.HttpRoute.prototype.hasOffloaded = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional string field_mask_root = 10;
 * @return {string}
 */
proto.yamcs.api.HttpRoute.prototype.getFieldMaskRoot = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.api.HttpRoute} returns this
 */
proto.yamcs.api.HttpRoute.prototype.setFieldMaskRoot = function(value) {
  return jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.api.HttpRoute} returns this
 */
proto.yamcs.api.HttpRoute.prototype.clearFieldMaskRoot = function() {
  return jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.api.HttpRoute.prototype.hasFieldMaskRoot = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * repeated HttpRoute additional_bindings = 11;
 * @return {!Array<!proto.yamcs.api.HttpRoute>}
 */
proto.yamcs.api.HttpRoute.prototype.getAdditionalBindingsList = function() {
  return /** @type{!Array<!proto.yamcs.api.HttpRoute>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.yamcs.api.HttpRoute, 11));
};


/**
 * @param {!Array<!proto.yamcs.api.HttpRoute>} value
 * @return {!proto.yamcs.api.HttpRoute} returns this
*/
proto.yamcs.api.HttpRoute.prototype.setAdditionalBindingsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.yamcs.api.HttpRoute=} opt_value
 * @param {number=} opt_index
 * @return {!proto.yamcs.api.HttpRoute}
 */
proto.yamcs.api.HttpRoute.prototype.addAdditionalBindings = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.yamcs.api.HttpRoute, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.yamcs.api.HttpRoute} returns this
 */
proto.yamcs.api.HttpRoute.prototype.clearAdditionalBindingsList = function() {
  return this.setAdditionalBindingsList([]);
};


/**
 * optional string log = 12;
 * @return {string}
 */
proto.yamcs.api.HttpRoute.prototype.getLog = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.api.HttpRoute} returns this
 */
proto.yamcs.api.HttpRoute.prototype.setLog = function(value) {
  return jspb.Message.setField(this, 12, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.api.HttpRoute} returns this
 */
proto.yamcs.api.HttpRoute.prototype.clearLog = function() {
  return jspb.Message.setField(this, 12, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.api.HttpRoute.prototype.hasLog = function() {
  return jspb.Message.getField(this, 12) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.yamcs.api.WebSocketTopic.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yamcs.api.WebSocketTopic.prototype.toObject = function(opt_includeInstance) {
  return proto.yamcs.api.WebSocketTopic.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yamcs.api.WebSocketTopic} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.api.WebSocketTopic.toObject = function(includeInstance, msg) {
  var f, obj = {
    topic: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    deprecated: (f = jspb.Message.getBooleanField(msg, 2)) == null ? undefined : f,
    additionalBindingsList: jspb.Message.toObjectList(msg.getAdditionalBindingsList(),
    proto.yamcs.api.WebSocketTopic.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yamcs.api.WebSocketTopic}
 */
proto.yamcs.api.WebSocketTopic.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yamcs.api.WebSocketTopic;
  return proto.yamcs.api.WebSocketTopic.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yamcs.api.WebSocketTopic} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yamcs.api.WebSocketTopic}
 */
proto.yamcs.api.WebSocketTopic.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTopic(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDeprecated(value);
      break;
    case 3:
      var value = new proto.yamcs.api.WebSocketTopic;
      reader.readMessage(value,proto.yamcs.api.WebSocketTopic.deserializeBinaryFromReader);
      msg.addAdditionalBindings(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yamcs.api.WebSocketTopic.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yamcs.api.WebSocketTopic.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yamcs.api.WebSocketTopic} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.api.WebSocketTopic.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getAdditionalBindingsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.yamcs.api.WebSocketTopic.serializeBinaryToWriter
    );
  }
};


/**
 * optional string topic = 1;
 * @return {string}
 */
proto.yamcs.api.WebSocketTopic.prototype.getTopic = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.api.WebSocketTopic} returns this
 */
proto.yamcs.api.WebSocketTopic.prototype.setTopic = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.api.WebSocketTopic} returns this
 */
proto.yamcs.api.WebSocketTopic.prototype.clearTopic = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.api.WebSocketTopic.prototype.hasTopic = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool deprecated = 2;
 * @return {boolean}
 */
proto.yamcs.api.WebSocketTopic.prototype.getDeprecated = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.yamcs.api.WebSocketTopic} returns this
 */
proto.yamcs.api.WebSocketTopic.prototype.setDeprecated = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.api.WebSocketTopic} returns this
 */
proto.yamcs.api.WebSocketTopic.prototype.clearDeprecated = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.api.WebSocketTopic.prototype.hasDeprecated = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated WebSocketTopic additional_bindings = 3;
 * @return {!Array<!proto.yamcs.api.WebSocketTopic>}
 */
proto.yamcs.api.WebSocketTopic.prototype.getAdditionalBindingsList = function() {
  return /** @type{!Array<!proto.yamcs.api.WebSocketTopic>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.yamcs.api.WebSocketTopic, 3));
};


/**
 * @param {!Array<!proto.yamcs.api.WebSocketTopic>} value
 * @return {!proto.yamcs.api.WebSocketTopic} returns this
*/
proto.yamcs.api.WebSocketTopic.prototype.setAdditionalBindingsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.yamcs.api.WebSocketTopic=} opt_value
 * @param {number=} opt_index
 * @return {!proto.yamcs.api.WebSocketTopic}
 */
proto.yamcs.api.WebSocketTopic.prototype.addAdditionalBindings = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.yamcs.api.WebSocketTopic, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.yamcs.api.WebSocketTopic} returns this
 */
proto.yamcs.api.WebSocketTopic.prototype.clearAdditionalBindingsList = function() {
  return this.setAdditionalBindingsList([]);
};


/**
 * @enum {number}
 */
proto.yamcs.api.FieldBehavior = {
  FIELD_BEHAVIOR_UNSPECIFIED: 0,
  SECRET: 1
};


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `label`.
 * @type {!jspb.ExtensionFieldInfo<string>}
 */
proto.yamcs.api.label = new jspb.ExtensionFieldInfo(
    2048,
    {label: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

google_protobuf_descriptor_pb.ServiceOptions.extensionsBinary[2048] = new jspb.ExtensionFieldBinaryInfo(
    proto.yamcs.api.label,
    jspb.BinaryReader.prototype.readString,
    jspb.BinaryWriter.prototype.writeString,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.ServiceOptions.extensions[2048] = proto.yamcs.api.label;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `route`.
 * @type {!jspb.ExtensionFieldInfo<!proto.yamcs.api.HttpRoute>}
 */
proto.yamcs.api.route = new jspb.ExtensionFieldInfo(
    6433,
    {route: 0},
    proto.yamcs.api.HttpRoute,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.yamcs.api.HttpRoute.toObject),
    0);

google_protobuf_descriptor_pb.MethodOptions.extensionsBinary[6433] = new jspb.ExtensionFieldBinaryInfo(
    proto.yamcs.api.route,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.yamcs.api.HttpRoute.serializeBinaryToWriter,
    proto.yamcs.api.HttpRoute.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MethodOptions.extensions[6433] = proto.yamcs.api.route;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `websocket`.
 * @type {!jspb.ExtensionFieldInfo<!proto.yamcs.api.WebSocketTopic>}
 */
proto.yamcs.api.websocket = new jspb.ExtensionFieldInfo(
    6443,
    {websocket: 0},
    proto.yamcs.api.WebSocketTopic,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.yamcs.api.WebSocketTopic.toObject),
    0);

google_protobuf_descriptor_pb.MethodOptions.extensionsBinary[6443] = new jspb.ExtensionFieldBinaryInfo(
    proto.yamcs.api.websocket,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.yamcs.api.WebSocketTopic.serializeBinaryToWriter,
    proto.yamcs.api.WebSocketTopic.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MethodOptions.extensions[6443] = proto.yamcs.api.websocket;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `fieldBehaviorList`.
 * @type {!jspb.ExtensionFieldInfo<!Array<!proto.yamcs.api.FieldBehavior>>}
 */
proto.yamcs.api.fieldBehaviorList = new jspb.ExtensionFieldInfo(
    6533,
    {fieldBehaviorList: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    1);

google_protobuf_descriptor_pb.FieldOptions.extensionsBinary[6533] = new jspb.ExtensionFieldBinaryInfo(
    proto.yamcs.api.fieldBehaviorList,
    jspb.BinaryReader.prototype.readEnum,
    jspb.BinaryWriter.prototype.writeRepeatedEnum,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.FieldOptions.extensions[6533] = proto.yamcs.api.fieldBehaviorList;

goog.object.extend(exports, proto.yamcs.api);
