// source: yamcs/protobuf/archive/rocksdb_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
var yamcs_api_annotations_pb = require('../../../yamcs/api/annotations_pb.js');
goog.object.extend(proto, yamcs_api_annotations_pb);
var yamcs_api_httpbody_pb = require('../../../yamcs/api/httpbody_pb.js');
goog.object.extend(proto, yamcs_api_httpbody_pb);
goog.exportSymbol('proto.yamcs.protobuf.archive.BackupDatabaseRequest', null, global);
goog.exportSymbol('proto.yamcs.protobuf.archive.CompactDatabaseRequest', null, global);
goog.exportSymbol('proto.yamcs.protobuf.archive.DescribeDatabaseRequest', null, global);
goog.exportSymbol('proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse', null, global);
goog.exportSymbol('proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse', null, global);
goog.exportSymbol('proto.yamcs.protobuf.archive.RocksDbDatabaseInfo', null, global);
goog.exportSymbol('proto.yamcs.protobuf.archive.RocksDbTablespaceInfo', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse.repeatedFields_, null);
};
goog.inherits(proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse.displayName = 'proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yamcs.protobuf.archive.RocksDbTablespaceInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.repeatedFields_, null);
};
goog.inherits(proto.yamcs.protobuf.archive.RocksDbTablespaceInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.displayName = 'proto.yamcs.protobuf.archive.RocksDbTablespaceInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse.repeatedFields_, null);
};
goog.inherits(proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse.displayName = 'proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yamcs.protobuf.archive.RocksDbDatabaseInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yamcs.protobuf.archive.RocksDbDatabaseInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.displayName = 'proto.yamcs.protobuf.archive.RocksDbDatabaseInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yamcs.protobuf.archive.BackupDatabaseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yamcs.protobuf.archive.BackupDatabaseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yamcs.protobuf.archive.BackupDatabaseRequest.displayName = 'proto.yamcs.protobuf.archive.BackupDatabaseRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yamcs.protobuf.archive.CompactDatabaseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yamcs.protobuf.archive.CompactDatabaseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yamcs.protobuf.archive.CompactDatabaseRequest.displayName = 'proto.yamcs.protobuf.archive.CompactDatabaseRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yamcs.protobuf.archive.DescribeDatabaseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yamcs.protobuf.archive.DescribeDatabaseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yamcs.protobuf.archive.DescribeDatabaseRequest.displayName = 'proto.yamcs.protobuf.archive.DescribeDatabaseRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    tablespacesList: jspb.Message.toObjectList(msg.getTablespacesList(),
    proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse}
 */
proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse;
  return proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse}
 */
proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.yamcs.protobuf.archive.RocksDbTablespaceInfo;
      reader.readMessage(value,proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.deserializeBinaryFromReader);
      msg.addTablespaces(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTablespacesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.serializeBinaryToWriter
    );
  }
};


/**
 * repeated RocksDbTablespaceInfo tablespaces = 1;
 * @return {!Array<!proto.yamcs.protobuf.archive.RocksDbTablespaceInfo>}
 */
proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse.prototype.getTablespacesList = function() {
  return /** @type{!Array<!proto.yamcs.protobuf.archive.RocksDbTablespaceInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.yamcs.protobuf.archive.RocksDbTablespaceInfo, 1));
};


/**
 * @param {!Array<!proto.yamcs.protobuf.archive.RocksDbTablespaceInfo>} value
 * @return {!proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse} returns this
*/
proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse.prototype.setTablespacesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.yamcs.protobuf.archive.RocksDbTablespaceInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.yamcs.protobuf.archive.RocksDbTablespaceInfo}
 */
proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse.prototype.addTablespaces = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.yamcs.protobuf.archive.RocksDbTablespaceInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse} returns this
 */
proto.yamcs.protobuf.archive.ListRocksDbTablespacesResponse.prototype.clearTablespacesList = function() {
  return this.setTablespacesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yamcs.protobuf.archive.RocksDbTablespaceInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    datadir: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    databasesList: jspb.Message.toObjectList(msg.getDatabasesList(),
    proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yamcs.protobuf.archive.RocksDbTablespaceInfo}
 */
proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yamcs.protobuf.archive.RocksDbTablespaceInfo;
  return proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yamcs.protobuf.archive.RocksDbTablespaceInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yamcs.protobuf.archive.RocksDbTablespaceInfo}
 */
proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDatadir(value);
      break;
    case 3:
      var value = new proto.yamcs.protobuf.archive.RocksDbDatabaseInfo;
      reader.readMessage(value,proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.deserializeBinaryFromReader);
      msg.addDatabases(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yamcs.protobuf.archive.RocksDbTablespaceInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDatabasesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.protobuf.archive.RocksDbTablespaceInfo} returns this
 */
proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.prototype.setName = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.archive.RocksDbTablespaceInfo} returns this
 */
proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.prototype.clearName = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.prototype.hasName = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string dataDir = 2;
 * @return {string}
 */
proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.prototype.getDatadir = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.protobuf.archive.RocksDbTablespaceInfo} returns this
 */
proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.prototype.setDatadir = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.archive.RocksDbTablespaceInfo} returns this
 */
proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.prototype.clearDatadir = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.prototype.hasDatadir = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated RocksDbDatabaseInfo databases = 3;
 * @return {!Array<!proto.yamcs.protobuf.archive.RocksDbDatabaseInfo>}
 */
proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.prototype.getDatabasesList = function() {
  return /** @type{!Array<!proto.yamcs.protobuf.archive.RocksDbDatabaseInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.yamcs.protobuf.archive.RocksDbDatabaseInfo, 3));
};


/**
 * @param {!Array<!proto.yamcs.protobuf.archive.RocksDbDatabaseInfo>} value
 * @return {!proto.yamcs.protobuf.archive.RocksDbTablespaceInfo} returns this
*/
proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.prototype.setDatabasesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.yamcs.protobuf.archive.RocksDbDatabaseInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.yamcs.protobuf.archive.RocksDbDatabaseInfo}
 */
proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.prototype.addDatabases = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.yamcs.protobuf.archive.RocksDbDatabaseInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.yamcs.protobuf.archive.RocksDbTablespaceInfo} returns this
 */
proto.yamcs.protobuf.archive.RocksDbTablespaceInfo.prototype.clearDatabasesList = function() {
  return this.setDatabasesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    databasesList: jspb.Message.toObjectList(msg.getDatabasesList(),
    proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse}
 */
proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse;
  return proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse}
 */
proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.yamcs.protobuf.archive.RocksDbDatabaseInfo;
      reader.readMessage(value,proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.deserializeBinaryFromReader);
      msg.addDatabases(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDatabasesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.serializeBinaryToWriter
    );
  }
};


/**
 * repeated RocksDbDatabaseInfo databases = 1;
 * @return {!Array<!proto.yamcs.protobuf.archive.RocksDbDatabaseInfo>}
 */
proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse.prototype.getDatabasesList = function() {
  return /** @type{!Array<!proto.yamcs.protobuf.archive.RocksDbDatabaseInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.yamcs.protobuf.archive.RocksDbDatabaseInfo, 1));
};


/**
 * @param {!Array<!proto.yamcs.protobuf.archive.RocksDbDatabaseInfo>} value
 * @return {!proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse} returns this
*/
proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse.prototype.setDatabasesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.yamcs.protobuf.archive.RocksDbDatabaseInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.yamcs.protobuf.archive.RocksDbDatabaseInfo}
 */
proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse.prototype.addDatabases = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.yamcs.protobuf.archive.RocksDbDatabaseInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse} returns this
 */
proto.yamcs.protobuf.archive.ListRocksDbDatabasesResponse.prototype.clearDatabasesList = function() {
  return this.setDatabasesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yamcs.protobuf.archive.RocksDbDatabaseInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    tablespace: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    datadir: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    dbpath: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yamcs.protobuf.archive.RocksDbDatabaseInfo}
 */
proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yamcs.protobuf.archive.RocksDbDatabaseInfo;
  return proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yamcs.protobuf.archive.RocksDbDatabaseInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yamcs.protobuf.archive.RocksDbDatabaseInfo}
 */
proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTablespace(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDatadir(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDbpath(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yamcs.protobuf.archive.RocksDbDatabaseInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string tablespace = 1;
 * @return {string}
 */
proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.prototype.getTablespace = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.protobuf.archive.RocksDbDatabaseInfo} returns this
 */
proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.prototype.setTablespace = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.archive.RocksDbDatabaseInfo} returns this
 */
proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.prototype.clearTablespace = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.prototype.hasTablespace = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string dataDir = 2;
 * @return {string}
 */
proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.prototype.getDatadir = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.protobuf.archive.RocksDbDatabaseInfo} returns this
 */
proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.prototype.setDatadir = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.archive.RocksDbDatabaseInfo} returns this
 */
proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.prototype.clearDatadir = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.prototype.hasDatadir = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string dbPath = 3;
 * @return {string}
 */
proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.prototype.getDbpath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.protobuf.archive.RocksDbDatabaseInfo} returns this
 */
proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.prototype.setDbpath = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.archive.RocksDbDatabaseInfo} returns this
 */
proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.prototype.clearDbpath = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.archive.RocksDbDatabaseInfo.prototype.hasDbpath = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yamcs.protobuf.archive.BackupDatabaseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.yamcs.protobuf.archive.BackupDatabaseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yamcs.protobuf.archive.BackupDatabaseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.archive.BackupDatabaseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    tablespace: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    dbpath: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    backupdir: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yamcs.protobuf.archive.BackupDatabaseRequest}
 */
proto.yamcs.protobuf.archive.BackupDatabaseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yamcs.protobuf.archive.BackupDatabaseRequest;
  return proto.yamcs.protobuf.archive.BackupDatabaseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yamcs.protobuf.archive.BackupDatabaseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yamcs.protobuf.archive.BackupDatabaseRequest}
 */
proto.yamcs.protobuf.archive.BackupDatabaseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTablespace(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDbpath(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBackupdir(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yamcs.protobuf.archive.BackupDatabaseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yamcs.protobuf.archive.BackupDatabaseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yamcs.protobuf.archive.BackupDatabaseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.archive.BackupDatabaseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string tablespace = 1;
 * @return {string}
 */
proto.yamcs.protobuf.archive.BackupDatabaseRequest.prototype.getTablespace = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.protobuf.archive.BackupDatabaseRequest} returns this
 */
proto.yamcs.protobuf.archive.BackupDatabaseRequest.prototype.setTablespace = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.archive.BackupDatabaseRequest} returns this
 */
proto.yamcs.protobuf.archive.BackupDatabaseRequest.prototype.clearTablespace = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.archive.BackupDatabaseRequest.prototype.hasTablespace = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string dbpath = 2;
 * @return {string}
 */
proto.yamcs.protobuf.archive.BackupDatabaseRequest.prototype.getDbpath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.protobuf.archive.BackupDatabaseRequest} returns this
 */
proto.yamcs.protobuf.archive.BackupDatabaseRequest.prototype.setDbpath = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.archive.BackupDatabaseRequest} returns this
 */
proto.yamcs.protobuf.archive.BackupDatabaseRequest.prototype.clearDbpath = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.archive.BackupDatabaseRequest.prototype.hasDbpath = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string backupDir = 3;
 * @return {string}
 */
proto.yamcs.protobuf.archive.BackupDatabaseRequest.prototype.getBackupdir = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.protobuf.archive.BackupDatabaseRequest} returns this
 */
proto.yamcs.protobuf.archive.BackupDatabaseRequest.prototype.setBackupdir = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.archive.BackupDatabaseRequest} returns this
 */
proto.yamcs.protobuf.archive.BackupDatabaseRequest.prototype.clearBackupdir = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.archive.BackupDatabaseRequest.prototype.hasBackupdir = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yamcs.protobuf.archive.CompactDatabaseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.yamcs.protobuf.archive.CompactDatabaseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yamcs.protobuf.archive.CompactDatabaseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.archive.CompactDatabaseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    tablespace: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    dbpath: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yamcs.protobuf.archive.CompactDatabaseRequest}
 */
proto.yamcs.protobuf.archive.CompactDatabaseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yamcs.protobuf.archive.CompactDatabaseRequest;
  return proto.yamcs.protobuf.archive.CompactDatabaseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yamcs.protobuf.archive.CompactDatabaseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yamcs.protobuf.archive.CompactDatabaseRequest}
 */
proto.yamcs.protobuf.archive.CompactDatabaseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTablespace(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDbpath(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yamcs.protobuf.archive.CompactDatabaseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yamcs.protobuf.archive.CompactDatabaseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yamcs.protobuf.archive.CompactDatabaseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.archive.CompactDatabaseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string tablespace = 1;
 * @return {string}
 */
proto.yamcs.protobuf.archive.CompactDatabaseRequest.prototype.getTablespace = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.protobuf.archive.CompactDatabaseRequest} returns this
 */
proto.yamcs.protobuf.archive.CompactDatabaseRequest.prototype.setTablespace = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.archive.CompactDatabaseRequest} returns this
 */
proto.yamcs.protobuf.archive.CompactDatabaseRequest.prototype.clearTablespace = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.archive.CompactDatabaseRequest.prototype.hasTablespace = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string dbpath = 2;
 * @return {string}
 */
proto.yamcs.protobuf.archive.CompactDatabaseRequest.prototype.getDbpath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.protobuf.archive.CompactDatabaseRequest} returns this
 */
proto.yamcs.protobuf.archive.CompactDatabaseRequest.prototype.setDbpath = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.archive.CompactDatabaseRequest} returns this
 */
proto.yamcs.protobuf.archive.CompactDatabaseRequest.prototype.clearDbpath = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.archive.CompactDatabaseRequest.prototype.hasDbpath = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yamcs.protobuf.archive.DescribeDatabaseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.yamcs.protobuf.archive.DescribeDatabaseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yamcs.protobuf.archive.DescribeDatabaseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.archive.DescribeDatabaseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    tablespace: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    dbpath: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yamcs.protobuf.archive.DescribeDatabaseRequest}
 */
proto.yamcs.protobuf.archive.DescribeDatabaseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yamcs.protobuf.archive.DescribeDatabaseRequest;
  return proto.yamcs.protobuf.archive.DescribeDatabaseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yamcs.protobuf.archive.DescribeDatabaseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yamcs.protobuf.archive.DescribeDatabaseRequest}
 */
proto.yamcs.protobuf.archive.DescribeDatabaseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTablespace(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDbpath(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yamcs.protobuf.archive.DescribeDatabaseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yamcs.protobuf.archive.DescribeDatabaseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yamcs.protobuf.archive.DescribeDatabaseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.archive.DescribeDatabaseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string tablespace = 1;
 * @return {string}
 */
proto.yamcs.protobuf.archive.DescribeDatabaseRequest.prototype.getTablespace = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.protobuf.archive.DescribeDatabaseRequest} returns this
 */
proto.yamcs.protobuf.archive.DescribeDatabaseRequest.prototype.setTablespace = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.archive.DescribeDatabaseRequest} returns this
 */
proto.yamcs.protobuf.archive.DescribeDatabaseRequest.prototype.clearTablespace = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.archive.DescribeDatabaseRequest.prototype.hasTablespace = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string dbpath = 2;
 * @return {string}
 */
proto.yamcs.protobuf.archive.DescribeDatabaseRequest.prototype.getDbpath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.protobuf.archive.DescribeDatabaseRequest} returns this
 */
proto.yamcs.protobuf.archive.DescribeDatabaseRequest.prototype.setDbpath = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.archive.DescribeDatabaseRequest} returns this
 */
proto.yamcs.protobuf.archive.DescribeDatabaseRequest.prototype.clearDbpath = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.archive.DescribeDatabaseRequest.prototype.hasDbpath = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.yamcs.protobuf.archive);
