name: npm install, build, and lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 18.x]
        openmct-version:
          - latest
          - stable
    timeout-minutes: 10
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Run build:example based on openmct-version
      run: |
        if [ "${{ matrix.openmct-version }}" = "latest" ]; then
          npm run build:example:master
        elif [ "${{ matrix.openmct-version }}" = "stable" ]; then
          npm run build:example
        fi

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - run: npm install
    - name: Run lint
      run: npm run lint
