// source: yamcs/protobuf/alarms/alarms.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var yamcs_protobuf_yamcs_pb = require('../../../yamcs/protobuf/yamcs_pb.js');
goog.object.extend(proto, yamcs_protobuf_yamcs_pb);
var yamcs_protobuf_mdb_mdb_pb = require('../../../yamcs/protobuf/mdb/mdb_pb.js');
goog.object.extend(proto, yamcs_protobuf_mdb_mdb_pb);
var yamcs_protobuf_pvalue_pvalue_pb = require('../../../yamcs/protobuf/pvalue/pvalue_pb.js');
goog.object.extend(proto, yamcs_protobuf_pvalue_pvalue_pb);
var yamcs_protobuf_events_events_pb = require('../../../yamcs/protobuf/events/events_pb.js');
goog.object.extend(proto, yamcs_protobuf_events_events_pb);
goog.exportSymbol('proto.yamcs.protobuf.alarms.AcknowledgeInfo', null, global);
goog.exportSymbol('proto.yamcs.protobuf.alarms.AlarmData', null, global);
goog.exportSymbol('proto.yamcs.protobuf.alarms.AlarmNotificationType', null, global);
goog.exportSymbol('proto.yamcs.protobuf.alarms.AlarmSeverity', null, global);
goog.exportSymbol('proto.yamcs.protobuf.alarms.AlarmType', null, global);
goog.exportSymbol('proto.yamcs.protobuf.alarms.ClearInfo', null, global);
goog.exportSymbol('proto.yamcs.protobuf.alarms.EventAlarmData', null, global);
goog.exportSymbol('proto.yamcs.protobuf.alarms.ParameterAlarmData', null, global);
goog.exportSymbol('proto.yamcs.protobuf.alarms.ShelveInfo', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yamcs.protobuf.alarms.AcknowledgeInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yamcs.protobuf.alarms.AcknowledgeInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yamcs.protobuf.alarms.AcknowledgeInfo.displayName = 'proto.yamcs.protobuf.alarms.AcknowledgeInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yamcs.protobuf.alarms.ShelveInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yamcs.protobuf.alarms.ShelveInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yamcs.protobuf.alarms.ShelveInfo.displayName = 'proto.yamcs.protobuf.alarms.ShelveInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yamcs.protobuf.alarms.ClearInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yamcs.protobuf.alarms.ClearInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yamcs.protobuf.alarms.ClearInfo.displayName = 'proto.yamcs.protobuf.alarms.ClearInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yamcs.protobuf.alarms.AlarmData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yamcs.protobuf.alarms.AlarmData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yamcs.protobuf.alarms.AlarmData.displayName = 'proto.yamcs.protobuf.alarms.AlarmData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yamcs.protobuf.alarms.ParameterAlarmData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yamcs.protobuf.alarms.ParameterAlarmData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yamcs.protobuf.alarms.ParameterAlarmData.displayName = 'proto.yamcs.protobuf.alarms.ParameterAlarmData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.yamcs.protobuf.alarms.EventAlarmData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.yamcs.protobuf.alarms.EventAlarmData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.yamcs.protobuf.alarms.EventAlarmData.displayName = 'proto.yamcs.protobuf.alarms.EventAlarmData';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yamcs.protobuf.alarms.AcknowledgeInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.yamcs.protobuf.alarms.AcknowledgeInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yamcs.protobuf.alarms.AcknowledgeInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.alarms.AcknowledgeInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    acknowledgedby: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    acknowledgemessage: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    acknowledgetime: (f = msg.getAcknowledgetime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yamcs.protobuf.alarms.AcknowledgeInfo}
 */
proto.yamcs.protobuf.alarms.AcknowledgeInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yamcs.protobuf.alarms.AcknowledgeInfo;
  return proto.yamcs.protobuf.alarms.AcknowledgeInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yamcs.protobuf.alarms.AcknowledgeInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yamcs.protobuf.alarms.AcknowledgeInfo}
 */
proto.yamcs.protobuf.alarms.AcknowledgeInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAcknowledgedby(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAcknowledgemessage(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setAcknowledgetime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yamcs.protobuf.alarms.AcknowledgeInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yamcs.protobuf.alarms.AcknowledgeInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yamcs.protobuf.alarms.AcknowledgeInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.alarms.AcknowledgeInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAcknowledgetime();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string acknowledgedBy = 1;
 * @return {string}
 */
proto.yamcs.protobuf.alarms.AcknowledgeInfo.prototype.getAcknowledgedby = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.protobuf.alarms.AcknowledgeInfo} returns this
 */
proto.yamcs.protobuf.alarms.AcknowledgeInfo.prototype.setAcknowledgedby = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.AcknowledgeInfo} returns this
 */
proto.yamcs.protobuf.alarms.AcknowledgeInfo.prototype.clearAcknowledgedby = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AcknowledgeInfo.prototype.hasAcknowledgedby = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string acknowledgeMessage = 2;
 * @return {string}
 */
proto.yamcs.protobuf.alarms.AcknowledgeInfo.prototype.getAcknowledgemessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.protobuf.alarms.AcknowledgeInfo} returns this
 */
proto.yamcs.protobuf.alarms.AcknowledgeInfo.prototype.setAcknowledgemessage = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.AcknowledgeInfo} returns this
 */
proto.yamcs.protobuf.alarms.AcknowledgeInfo.prototype.clearAcknowledgemessage = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AcknowledgeInfo.prototype.hasAcknowledgemessage = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp acknowledgeTime = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.yamcs.protobuf.alarms.AcknowledgeInfo.prototype.getAcknowledgetime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.yamcs.protobuf.alarms.AcknowledgeInfo} returns this
*/
proto.yamcs.protobuf.alarms.AcknowledgeInfo.prototype.setAcknowledgetime = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.AcknowledgeInfo} returns this
 */
proto.yamcs.protobuf.alarms.AcknowledgeInfo.prototype.clearAcknowledgetime = function() {
  return this.setAcknowledgetime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AcknowledgeInfo.prototype.hasAcknowledgetime = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yamcs.protobuf.alarms.ShelveInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.yamcs.protobuf.alarms.ShelveInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yamcs.protobuf.alarms.ShelveInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.alarms.ShelveInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    shelvedby: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    shelvemessage: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    shelvetime: (f = msg.getShelvetime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    shelveexpiration: (f = msg.getShelveexpiration()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yamcs.protobuf.alarms.ShelveInfo}
 */
proto.yamcs.protobuf.alarms.ShelveInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yamcs.protobuf.alarms.ShelveInfo;
  return proto.yamcs.protobuf.alarms.ShelveInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yamcs.protobuf.alarms.ShelveInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yamcs.protobuf.alarms.ShelveInfo}
 */
proto.yamcs.protobuf.alarms.ShelveInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setShelvedby(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setShelvemessage(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setShelvetime(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setShelveexpiration(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yamcs.protobuf.alarms.ShelveInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yamcs.protobuf.alarms.ShelveInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yamcs.protobuf.alarms.ShelveInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.alarms.ShelveInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getShelvetime();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getShelveexpiration();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string shelvedBy = 1;
 * @return {string}
 */
proto.yamcs.protobuf.alarms.ShelveInfo.prototype.getShelvedby = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.protobuf.alarms.ShelveInfo} returns this
 */
proto.yamcs.protobuf.alarms.ShelveInfo.prototype.setShelvedby = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.ShelveInfo} returns this
 */
proto.yamcs.protobuf.alarms.ShelveInfo.prototype.clearShelvedby = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.ShelveInfo.prototype.hasShelvedby = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string shelveMessage = 2;
 * @return {string}
 */
proto.yamcs.protobuf.alarms.ShelveInfo.prototype.getShelvemessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.protobuf.alarms.ShelveInfo} returns this
 */
proto.yamcs.protobuf.alarms.ShelveInfo.prototype.setShelvemessage = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.ShelveInfo} returns this
 */
proto.yamcs.protobuf.alarms.ShelveInfo.prototype.clearShelvemessage = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.ShelveInfo.prototype.hasShelvemessage = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp shelveTime = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.yamcs.protobuf.alarms.ShelveInfo.prototype.getShelvetime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.yamcs.protobuf.alarms.ShelveInfo} returns this
*/
proto.yamcs.protobuf.alarms.ShelveInfo.prototype.setShelvetime = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.ShelveInfo} returns this
 */
proto.yamcs.protobuf.alarms.ShelveInfo.prototype.clearShelvetime = function() {
  return this.setShelvetime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.ShelveInfo.prototype.hasShelvetime = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.Timestamp shelveExpiration = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.yamcs.protobuf.alarms.ShelveInfo.prototype.getShelveexpiration = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.yamcs.protobuf.alarms.ShelveInfo} returns this
*/
proto.yamcs.protobuf.alarms.ShelveInfo.prototype.setShelveexpiration = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.ShelveInfo} returns this
 */
proto.yamcs.protobuf.alarms.ShelveInfo.prototype.clearShelveexpiration = function() {
  return this.setShelveexpiration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.ShelveInfo.prototype.hasShelveexpiration = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yamcs.protobuf.alarms.ClearInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.yamcs.protobuf.alarms.ClearInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yamcs.protobuf.alarms.ClearInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.alarms.ClearInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    clearedby: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    cleartime: (f = msg.getCleartime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    clearmessage: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yamcs.protobuf.alarms.ClearInfo}
 */
proto.yamcs.protobuf.alarms.ClearInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yamcs.protobuf.alarms.ClearInfo;
  return proto.yamcs.protobuf.alarms.ClearInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yamcs.protobuf.alarms.ClearInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yamcs.protobuf.alarms.ClearInfo}
 */
proto.yamcs.protobuf.alarms.ClearInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setClearedby(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCleartime(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setClearmessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yamcs.protobuf.alarms.ClearInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yamcs.protobuf.alarms.ClearInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yamcs.protobuf.alarms.ClearInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.alarms.ClearInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCleartime();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string clearedBy = 1;
 * @return {string}
 */
proto.yamcs.protobuf.alarms.ClearInfo.prototype.getClearedby = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.protobuf.alarms.ClearInfo} returns this
 */
proto.yamcs.protobuf.alarms.ClearInfo.prototype.setClearedby = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.ClearInfo} returns this
 */
proto.yamcs.protobuf.alarms.ClearInfo.prototype.clearClearedby = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.ClearInfo.prototype.hasClearedby = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Timestamp clearTime = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.yamcs.protobuf.alarms.ClearInfo.prototype.getCleartime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.yamcs.protobuf.alarms.ClearInfo} returns this
*/
proto.yamcs.protobuf.alarms.ClearInfo.prototype.setCleartime = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.ClearInfo} returns this
 */
proto.yamcs.protobuf.alarms.ClearInfo.prototype.clearCleartime = function() {
  return this.setCleartime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.ClearInfo.prototype.hasCleartime = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string clearMessage = 3;
 * @return {string}
 */
proto.yamcs.protobuf.alarms.ClearInfo.prototype.getClearmessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.yamcs.protobuf.alarms.ClearInfo} returns this
 */
proto.yamcs.protobuf.alarms.ClearInfo.prototype.setClearmessage = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.ClearInfo} returns this
 */
proto.yamcs.protobuf.alarms.ClearInfo.prototype.clearClearmessage = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.ClearInfo.prototype.hasClearmessage = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.toObject = function(opt_includeInstance) {
  return proto.yamcs.protobuf.alarms.AlarmData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yamcs.protobuf.alarms.AlarmData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.alarms.AlarmData.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    triggertime: (f = msg.getTriggertime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    id: (f = msg.getId()) && yamcs_protobuf_yamcs_pb.NamedObjectId.toObject(includeInstance, f),
    seqnum: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
    severity: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f,
    violations: (f = jspb.Message.getField(msg, 6)) == null ? undefined : f,
    count: (f = jspb.Message.getField(msg, 7)) == null ? undefined : f,
    acknowledgeinfo: (f = msg.getAcknowledgeinfo()) && proto.yamcs.protobuf.alarms.AcknowledgeInfo.toObject(includeInstance, f),
    notificationtype: (f = jspb.Message.getField(msg, 9)) == null ? undefined : f,
    parameterdetail: (f = msg.getParameterdetail()) && proto.yamcs.protobuf.alarms.ParameterAlarmData.toObject(includeInstance, f),
    eventdetail: (f = msg.getEventdetail()) && proto.yamcs.protobuf.alarms.EventAlarmData.toObject(includeInstance, f),
    latching: (f = jspb.Message.getBooleanField(msg, 12)) == null ? undefined : f,
    processok: (f = jspb.Message.getBooleanField(msg, 13)) == null ? undefined : f,
    triggered: (f = jspb.Message.getBooleanField(msg, 14)) == null ? undefined : f,
    acknowledged: (f = jspb.Message.getBooleanField(msg, 15)) == null ? undefined : f,
    shelveinfo: (f = msg.getShelveinfo()) && proto.yamcs.protobuf.alarms.ShelveInfo.toObject(includeInstance, f),
    clearinfo: (f = msg.getClearinfo()) && proto.yamcs.protobuf.alarms.ClearInfo.toObject(includeInstance, f),
    updatetime: (f = msg.getUpdatetime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yamcs.protobuf.alarms.AlarmData}
 */
proto.yamcs.protobuf.alarms.AlarmData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yamcs.protobuf.alarms.AlarmData;
  return proto.yamcs.protobuf.alarms.AlarmData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yamcs.protobuf.alarms.AlarmData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yamcs.protobuf.alarms.AlarmData}
 */
proto.yamcs.protobuf.alarms.AlarmData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.yamcs.protobuf.alarms.AlarmType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTriggertime(value);
      break;
    case 3:
      var value = new yamcs_protobuf_yamcs_pb.NamedObjectId;
      reader.readMessage(value,yamcs_protobuf_yamcs_pb.NamedObjectId.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSeqnum(value);
      break;
    case 5:
      var value = /** @type {!proto.yamcs.protobuf.alarms.AlarmSeverity} */ (reader.readEnum());
      msg.setSeverity(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setViolations(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCount(value);
      break;
    case 8:
      var value = new proto.yamcs.protobuf.alarms.AcknowledgeInfo;
      reader.readMessage(value,proto.yamcs.protobuf.alarms.AcknowledgeInfo.deserializeBinaryFromReader);
      msg.setAcknowledgeinfo(value);
      break;
    case 9:
      var value = /** @type {!proto.yamcs.protobuf.alarms.AlarmNotificationType} */ (reader.readEnum());
      msg.setNotificationtype(value);
      break;
    case 10:
      var value = new proto.yamcs.protobuf.alarms.ParameterAlarmData;
      reader.readMessage(value,proto.yamcs.protobuf.alarms.ParameterAlarmData.deserializeBinaryFromReader);
      msg.setParameterdetail(value);
      break;
    case 11:
      var value = new proto.yamcs.protobuf.alarms.EventAlarmData;
      reader.readMessage(value,proto.yamcs.protobuf.alarms.EventAlarmData.deserializeBinaryFromReader);
      msg.setEventdetail(value);
      break;
    case 12:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setLatching(value);
      break;
    case 13:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setProcessok(value);
      break;
    case 14:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTriggered(value);
      break;
    case 15:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAcknowledged(value);
      break;
    case 16:
      var value = new proto.yamcs.protobuf.alarms.ShelveInfo;
      reader.readMessage(value,proto.yamcs.protobuf.alarms.ShelveInfo.deserializeBinaryFromReader);
      msg.setShelveinfo(value);
      break;
    case 17:
      var value = new proto.yamcs.protobuf.alarms.ClearInfo;
      reader.readMessage(value,proto.yamcs.protobuf.alarms.ClearInfo.deserializeBinaryFromReader);
      msg.setClearinfo(value);
      break;
    case 18:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatetime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yamcs.protobuf.alarms.AlarmData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yamcs.protobuf.alarms.AlarmData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.alarms.AlarmData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.yamcs.protobuf.alarms.AlarmType} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getTriggertime();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      yamcs_protobuf_yamcs_pb.NamedObjectId.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = /** @type {!proto.yamcs.protobuf.alarms.AlarmSeverity} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeUint32(
      7,
      f
    );
  }
  f = message.getAcknowledgeinfo();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.yamcs.protobuf.alarms.AcknowledgeInfo.serializeBinaryToWriter
    );
  }
  f = /** @type {!proto.yamcs.protobuf.alarms.AlarmNotificationType} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeEnum(
      9,
      f
    );
  }
  f = message.getParameterdetail();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.yamcs.protobuf.alarms.ParameterAlarmData.serializeBinaryToWriter
    );
  }
  f = message.getEventdetail();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.yamcs.protobuf.alarms.EventAlarmData.serializeBinaryToWriter
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 12));
  if (f != null) {
    writer.writeBool(
      12,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 13));
  if (f != null) {
    writer.writeBool(
      13,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 14));
  if (f != null) {
    writer.writeBool(
      14,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 15));
  if (f != null) {
    writer.writeBool(
      15,
      f
    );
  }
  f = message.getShelveinfo();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      proto.yamcs.protobuf.alarms.ShelveInfo.serializeBinaryToWriter
    );
  }
  f = message.getClearinfo();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      proto.yamcs.protobuf.alarms.ClearInfo.serializeBinaryToWriter
    );
  }
  f = message.getUpdatetime();
  if (f != null) {
    writer.writeMessage(
      18,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional AlarmType type = 1;
 * @return {!proto.yamcs.protobuf.alarms.AlarmType}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.getType = function() {
  return /** @type {!proto.yamcs.protobuf.alarms.AlarmType} */ (jspb.Message.getFieldWithDefault(this, 1, 1));
};


/**
 * @param {!proto.yamcs.protobuf.alarms.AlarmType} value
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.setType = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.clearType = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.hasType = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Timestamp triggerTime = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.getTriggertime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
*/
proto.yamcs.protobuf.alarms.AlarmData.prototype.setTriggertime = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.clearTriggertime = function() {
  return this.setTriggertime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.hasTriggertime = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional yamcs.protobuf.NamedObjectId id = 3;
 * @return {?proto.yamcs.protobuf.NamedObjectId}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.getId = function() {
  return /** @type{?proto.yamcs.protobuf.NamedObjectId} */ (
    jspb.Message.getWrapperField(this, yamcs_protobuf_yamcs_pb.NamedObjectId, 3));
};


/**
 * @param {?proto.yamcs.protobuf.NamedObjectId|undefined} value
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
*/
proto.yamcs.protobuf.alarms.AlarmData.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.hasId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional uint32 seqNum = 4;
 * @return {number}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.getSeqnum = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.setSeqnum = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.clearSeqnum = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.hasSeqnum = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional AlarmSeverity severity = 5;
 * @return {!proto.yamcs.protobuf.alarms.AlarmSeverity}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.getSeverity = function() {
  return /** @type {!proto.yamcs.protobuf.alarms.AlarmSeverity} */ (jspb.Message.getFieldWithDefault(this, 5, 1));
};


/**
 * @param {!proto.yamcs.protobuf.alarms.AlarmSeverity} value
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.setSeverity = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.clearSeverity = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.hasSeverity = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional uint32 violations = 6;
 * @return {number}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.getViolations = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.setViolations = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.clearViolations = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.hasViolations = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional uint32 count = 7;
 * @return {number}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.getCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.setCount = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.clearCount = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.hasCount = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional AcknowledgeInfo acknowledgeInfo = 8;
 * @return {?proto.yamcs.protobuf.alarms.AcknowledgeInfo}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.getAcknowledgeinfo = function() {
  return /** @type{?proto.yamcs.protobuf.alarms.AcknowledgeInfo} */ (
    jspb.Message.getWrapperField(this, proto.yamcs.protobuf.alarms.AcknowledgeInfo, 8));
};


/**
 * @param {?proto.yamcs.protobuf.alarms.AcknowledgeInfo|undefined} value
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
*/
proto.yamcs.protobuf.alarms.AlarmData.prototype.setAcknowledgeinfo = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.clearAcknowledgeinfo = function() {
  return this.setAcknowledgeinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.hasAcknowledgeinfo = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional AlarmNotificationType notificationType = 9;
 * @return {!proto.yamcs.protobuf.alarms.AlarmNotificationType}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.getNotificationtype = function() {
  return /** @type {!proto.yamcs.protobuf.alarms.AlarmNotificationType} */ (jspb.Message.getFieldWithDefault(this, 9, 1));
};


/**
 * @param {!proto.yamcs.protobuf.alarms.AlarmNotificationType} value
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.setNotificationtype = function(value) {
  return jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.clearNotificationtype = function() {
  return jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.hasNotificationtype = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional ParameterAlarmData parameterDetail = 10;
 * @return {?proto.yamcs.protobuf.alarms.ParameterAlarmData}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.getParameterdetail = function() {
  return /** @type{?proto.yamcs.protobuf.alarms.ParameterAlarmData} */ (
    jspb.Message.getWrapperField(this, proto.yamcs.protobuf.alarms.ParameterAlarmData, 10));
};


/**
 * @param {?proto.yamcs.protobuf.alarms.ParameterAlarmData|undefined} value
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
*/
proto.yamcs.protobuf.alarms.AlarmData.prototype.setParameterdetail = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.clearParameterdetail = function() {
  return this.setParameterdetail(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.hasParameterdetail = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional EventAlarmData eventDetail = 11;
 * @return {?proto.yamcs.protobuf.alarms.EventAlarmData}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.getEventdetail = function() {
  return /** @type{?proto.yamcs.protobuf.alarms.EventAlarmData} */ (
    jspb.Message.getWrapperField(this, proto.yamcs.protobuf.alarms.EventAlarmData, 11));
};


/**
 * @param {?proto.yamcs.protobuf.alarms.EventAlarmData|undefined} value
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
*/
proto.yamcs.protobuf.alarms.AlarmData.prototype.setEventdetail = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.clearEventdetail = function() {
  return this.setEventdetail(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.hasEventdetail = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional bool latching = 12;
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.getLatching = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 12, false));
};


/**
 * @param {boolean} value
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.setLatching = function(value) {
  return jspb.Message.setField(this, 12, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.clearLatching = function() {
  return jspb.Message.setField(this, 12, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.hasLatching = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional bool processOK = 13;
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.getProcessok = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 13, false));
};


/**
 * @param {boolean} value
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.setProcessok = function(value) {
  return jspb.Message.setField(this, 13, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.clearProcessok = function() {
  return jspb.Message.setField(this, 13, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.hasProcessok = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional bool triggered = 14;
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.getTriggered = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 14, false));
};


/**
 * @param {boolean} value
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.setTriggered = function(value) {
  return jspb.Message.setField(this, 14, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.clearTriggered = function() {
  return jspb.Message.setField(this, 14, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.hasTriggered = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional bool acknowledged = 15;
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.getAcknowledged = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 15, false));
};


/**
 * @param {boolean} value
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.setAcknowledged = function(value) {
  return jspb.Message.setField(this, 15, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.clearAcknowledged = function() {
  return jspb.Message.setField(this, 15, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.hasAcknowledged = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional ShelveInfo shelveInfo = 16;
 * @return {?proto.yamcs.protobuf.alarms.ShelveInfo}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.getShelveinfo = function() {
  return /** @type{?proto.yamcs.protobuf.alarms.ShelveInfo} */ (
    jspb.Message.getWrapperField(this, proto.yamcs.protobuf.alarms.ShelveInfo, 16));
};


/**
 * @param {?proto.yamcs.protobuf.alarms.ShelveInfo|undefined} value
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
*/
proto.yamcs.protobuf.alarms.AlarmData.prototype.setShelveinfo = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.clearShelveinfo = function() {
  return this.setShelveinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.hasShelveinfo = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional ClearInfo clearInfo = 17;
 * @return {?proto.yamcs.protobuf.alarms.ClearInfo}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.getClearinfo = function() {
  return /** @type{?proto.yamcs.protobuf.alarms.ClearInfo} */ (
    jspb.Message.getWrapperField(this, proto.yamcs.protobuf.alarms.ClearInfo, 17));
};


/**
 * @param {?proto.yamcs.protobuf.alarms.ClearInfo|undefined} value
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
*/
proto.yamcs.protobuf.alarms.AlarmData.prototype.setClearinfo = function(value) {
  return jspb.Message.setWrapperField(this, 17, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.clearClearinfo = function() {
  return this.setClearinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.hasClearinfo = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional google.protobuf.Timestamp updateTime = 18;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.getUpdatetime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 18));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
*/
proto.yamcs.protobuf.alarms.AlarmData.prototype.setUpdatetime = function(value) {
  return jspb.Message.setWrapperField(this, 18, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.AlarmData} returns this
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.clearUpdatetime = function() {
  return this.setUpdatetime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.AlarmData.prototype.hasUpdatetime = function() {
  return jspb.Message.getField(this, 18) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yamcs.protobuf.alarms.ParameterAlarmData.prototype.toObject = function(opt_includeInstance) {
  return proto.yamcs.protobuf.alarms.ParameterAlarmData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yamcs.protobuf.alarms.ParameterAlarmData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.alarms.ParameterAlarmData.toObject = function(includeInstance, msg) {
  var f, obj = {
    triggervalue: (f = msg.getTriggervalue()) && yamcs_protobuf_pvalue_pvalue_pb.ParameterValue.toObject(includeInstance, f),
    mostseverevalue: (f = msg.getMostseverevalue()) && yamcs_protobuf_pvalue_pvalue_pb.ParameterValue.toObject(includeInstance, f),
    currentvalue: (f = msg.getCurrentvalue()) && yamcs_protobuf_pvalue_pvalue_pb.ParameterValue.toObject(includeInstance, f),
    parameter: (f = msg.getParameter()) && yamcs_protobuf_mdb_mdb_pb.ParameterInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yamcs.protobuf.alarms.ParameterAlarmData}
 */
proto.yamcs.protobuf.alarms.ParameterAlarmData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yamcs.protobuf.alarms.ParameterAlarmData;
  return proto.yamcs.protobuf.alarms.ParameterAlarmData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yamcs.protobuf.alarms.ParameterAlarmData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yamcs.protobuf.alarms.ParameterAlarmData}
 */
proto.yamcs.protobuf.alarms.ParameterAlarmData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new yamcs_protobuf_pvalue_pvalue_pb.ParameterValue;
      reader.readMessage(value,yamcs_protobuf_pvalue_pvalue_pb.ParameterValue.deserializeBinaryFromReader);
      msg.setTriggervalue(value);
      break;
    case 2:
      var value = new yamcs_protobuf_pvalue_pvalue_pb.ParameterValue;
      reader.readMessage(value,yamcs_protobuf_pvalue_pvalue_pb.ParameterValue.deserializeBinaryFromReader);
      msg.setMostseverevalue(value);
      break;
    case 3:
      var value = new yamcs_protobuf_pvalue_pvalue_pb.ParameterValue;
      reader.readMessage(value,yamcs_protobuf_pvalue_pvalue_pb.ParameterValue.deserializeBinaryFromReader);
      msg.setCurrentvalue(value);
      break;
    case 4:
      var value = new yamcs_protobuf_mdb_mdb_pb.ParameterInfo;
      reader.readMessage(value,yamcs_protobuf_mdb_mdb_pb.ParameterInfo.deserializeBinaryFromReader);
      msg.setParameter(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yamcs.protobuf.alarms.ParameterAlarmData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yamcs.protobuf.alarms.ParameterAlarmData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yamcs.protobuf.alarms.ParameterAlarmData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.alarms.ParameterAlarmData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTriggervalue();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      yamcs_protobuf_pvalue_pvalue_pb.ParameterValue.serializeBinaryToWriter
    );
  }
  f = message.getMostseverevalue();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      yamcs_protobuf_pvalue_pvalue_pb.ParameterValue.serializeBinaryToWriter
    );
  }
  f = message.getCurrentvalue();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      yamcs_protobuf_pvalue_pvalue_pb.ParameterValue.serializeBinaryToWriter
    );
  }
  f = message.getParameter();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      yamcs_protobuf_mdb_mdb_pb.ParameterInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional yamcs.protobuf.pvalue.ParameterValue triggerValue = 1;
 * @return {?proto.yamcs.protobuf.pvalue.ParameterValue}
 */
proto.yamcs.protobuf.alarms.ParameterAlarmData.prototype.getTriggervalue = function() {
  return /** @type{?proto.yamcs.protobuf.pvalue.ParameterValue} */ (
    jspb.Message.getWrapperField(this, yamcs_protobuf_pvalue_pvalue_pb.ParameterValue, 1));
};


/**
 * @param {?proto.yamcs.protobuf.pvalue.ParameterValue|undefined} value
 * @return {!proto.yamcs.protobuf.alarms.ParameterAlarmData} returns this
*/
proto.yamcs.protobuf.alarms.ParameterAlarmData.prototype.setTriggervalue = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.ParameterAlarmData} returns this
 */
proto.yamcs.protobuf.alarms.ParameterAlarmData.prototype.clearTriggervalue = function() {
  return this.setTriggervalue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.ParameterAlarmData.prototype.hasTriggervalue = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional yamcs.protobuf.pvalue.ParameterValue mostSevereValue = 2;
 * @return {?proto.yamcs.protobuf.pvalue.ParameterValue}
 */
proto.yamcs.protobuf.alarms.ParameterAlarmData.prototype.getMostseverevalue = function() {
  return /** @type{?proto.yamcs.protobuf.pvalue.ParameterValue} */ (
    jspb.Message.getWrapperField(this, yamcs_protobuf_pvalue_pvalue_pb.ParameterValue, 2));
};


/**
 * @param {?proto.yamcs.protobuf.pvalue.ParameterValue|undefined} value
 * @return {!proto.yamcs.protobuf.alarms.ParameterAlarmData} returns this
*/
proto.yamcs.protobuf.alarms.ParameterAlarmData.prototype.setMostseverevalue = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.ParameterAlarmData} returns this
 */
proto.yamcs.protobuf.alarms.ParameterAlarmData.prototype.clearMostseverevalue = function() {
  return this.setMostseverevalue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.ParameterAlarmData.prototype.hasMostseverevalue = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional yamcs.protobuf.pvalue.ParameterValue currentValue = 3;
 * @return {?proto.yamcs.protobuf.pvalue.ParameterValue}
 */
proto.yamcs.protobuf.alarms.ParameterAlarmData.prototype.getCurrentvalue = function() {
  return /** @type{?proto.yamcs.protobuf.pvalue.ParameterValue} */ (
    jspb.Message.getWrapperField(this, yamcs_protobuf_pvalue_pvalue_pb.ParameterValue, 3));
};


/**
 * @param {?proto.yamcs.protobuf.pvalue.ParameterValue|undefined} value
 * @return {!proto.yamcs.protobuf.alarms.ParameterAlarmData} returns this
*/
proto.yamcs.protobuf.alarms.ParameterAlarmData.prototype.setCurrentvalue = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.ParameterAlarmData} returns this
 */
proto.yamcs.protobuf.alarms.ParameterAlarmData.prototype.clearCurrentvalue = function() {
  return this.setCurrentvalue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.ParameterAlarmData.prototype.hasCurrentvalue = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional yamcs.protobuf.mdb.ParameterInfo parameter = 4;
 * @return {?proto.yamcs.protobuf.mdb.ParameterInfo}
 */
proto.yamcs.protobuf.alarms.ParameterAlarmData.prototype.getParameter = function() {
  return /** @type{?proto.yamcs.protobuf.mdb.ParameterInfo} */ (
    jspb.Message.getWrapperField(this, yamcs_protobuf_mdb_mdb_pb.ParameterInfo, 4));
};


/**
 * @param {?proto.yamcs.protobuf.mdb.ParameterInfo|undefined} value
 * @return {!proto.yamcs.protobuf.alarms.ParameterAlarmData} returns this
*/
proto.yamcs.protobuf.alarms.ParameterAlarmData.prototype.setParameter = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.ParameterAlarmData} returns this
 */
proto.yamcs.protobuf.alarms.ParameterAlarmData.prototype.clearParameter = function() {
  return this.setParameter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.ParameterAlarmData.prototype.hasParameter = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.yamcs.protobuf.alarms.EventAlarmData.prototype.toObject = function(opt_includeInstance) {
  return proto.yamcs.protobuf.alarms.EventAlarmData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.yamcs.protobuf.alarms.EventAlarmData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.alarms.EventAlarmData.toObject = function(includeInstance, msg) {
  var f, obj = {
    triggerevent: (f = msg.getTriggerevent()) && yamcs_protobuf_events_events_pb.Event.toObject(includeInstance, f),
    mostsevereevent: (f = msg.getMostsevereevent()) && yamcs_protobuf_events_events_pb.Event.toObject(includeInstance, f),
    currentevent: (f = msg.getCurrentevent()) && yamcs_protobuf_events_events_pb.Event.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.yamcs.protobuf.alarms.EventAlarmData}
 */
proto.yamcs.protobuf.alarms.EventAlarmData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.yamcs.protobuf.alarms.EventAlarmData;
  return proto.yamcs.protobuf.alarms.EventAlarmData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.yamcs.protobuf.alarms.EventAlarmData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.yamcs.protobuf.alarms.EventAlarmData}
 */
proto.yamcs.protobuf.alarms.EventAlarmData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new yamcs_protobuf_events_events_pb.Event;
      reader.readMessage(value,yamcs_protobuf_events_events_pb.Event.deserializeBinaryFromReader);
      msg.setTriggerevent(value);
      break;
    case 2:
      var value = new yamcs_protobuf_events_events_pb.Event;
      reader.readMessage(value,yamcs_protobuf_events_events_pb.Event.deserializeBinaryFromReader);
      msg.setMostsevereevent(value);
      break;
    case 3:
      var value = new yamcs_protobuf_events_events_pb.Event;
      reader.readMessage(value,yamcs_protobuf_events_events_pb.Event.deserializeBinaryFromReader);
      msg.setCurrentevent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.yamcs.protobuf.alarms.EventAlarmData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.yamcs.protobuf.alarms.EventAlarmData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.yamcs.protobuf.alarms.EventAlarmData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.yamcs.protobuf.alarms.EventAlarmData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTriggerevent();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      yamcs_protobuf_events_events_pb.Event.serializeBinaryToWriter
    );
  }
  f = message.getMostsevereevent();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      yamcs_protobuf_events_events_pb.Event.serializeBinaryToWriter
    );
  }
  f = message.getCurrentevent();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      yamcs_protobuf_events_events_pb.Event.serializeBinaryToWriter
    );
  }
};


/**
 * optional yamcs.protobuf.events.Event triggerEvent = 1;
 * @return {?proto.yamcs.protobuf.events.Event}
 */
proto.yamcs.protobuf.alarms.EventAlarmData.prototype.getTriggerevent = function() {
  return /** @type{?proto.yamcs.protobuf.events.Event} */ (
    jspb.Message.getWrapperField(this, yamcs_protobuf_events_events_pb.Event, 1));
};


/**
 * @param {?proto.yamcs.protobuf.events.Event|undefined} value
 * @return {!proto.yamcs.protobuf.alarms.EventAlarmData} returns this
*/
proto.yamcs.protobuf.alarms.EventAlarmData.prototype.setTriggerevent = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.EventAlarmData} returns this
 */
proto.yamcs.protobuf.alarms.EventAlarmData.prototype.clearTriggerevent = function() {
  return this.setTriggerevent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.EventAlarmData.prototype.hasTriggerevent = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional yamcs.protobuf.events.Event mostSevereEvent = 2;
 * @return {?proto.yamcs.protobuf.events.Event}
 */
proto.yamcs.protobuf.alarms.EventAlarmData.prototype.getMostsevereevent = function() {
  return /** @type{?proto.yamcs.protobuf.events.Event} */ (
    jspb.Message.getWrapperField(this, yamcs_protobuf_events_events_pb.Event, 2));
};


/**
 * @param {?proto.yamcs.protobuf.events.Event|undefined} value
 * @return {!proto.yamcs.protobuf.alarms.EventAlarmData} returns this
*/
proto.yamcs.protobuf.alarms.EventAlarmData.prototype.setMostsevereevent = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.EventAlarmData} returns this
 */
proto.yamcs.protobuf.alarms.EventAlarmData.prototype.clearMostsevereevent = function() {
  return this.setMostsevereevent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.EventAlarmData.prototype.hasMostsevereevent = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional yamcs.protobuf.events.Event currentEvent = 3;
 * @return {?proto.yamcs.protobuf.events.Event}
 */
proto.yamcs.protobuf.alarms.EventAlarmData.prototype.getCurrentevent = function() {
  return /** @type{?proto.yamcs.protobuf.events.Event} */ (
    jspb.Message.getWrapperField(this, yamcs_protobuf_events_events_pb.Event, 3));
};


/**
 * @param {?proto.yamcs.protobuf.events.Event|undefined} value
 * @return {!proto.yamcs.protobuf.alarms.EventAlarmData} returns this
*/
proto.yamcs.protobuf.alarms.EventAlarmData.prototype.setCurrentevent = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.yamcs.protobuf.alarms.EventAlarmData} returns this
 */
proto.yamcs.protobuf.alarms.EventAlarmData.prototype.clearCurrentevent = function() {
  return this.setCurrentevent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.yamcs.protobuf.alarms.EventAlarmData.prototype.hasCurrentevent = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * @enum {number}
 */
proto.yamcs.protobuf.alarms.AlarmNotificationType = {
  ACTIVE: 1,
  TRIGGERED: 2,
  SEVERITY_INCREASED: 3,
  VALUE_UPDATED: 4,
  ACKNOWLEDGED: 5,
  CLEARED: 6,
  RTN: 7,
  SHELVED: 8,
  UNSHELVED: 9,
  RESET: 10
};

/**
 * @enum {number}
 */
proto.yamcs.protobuf.alarms.AlarmType = {
  PARAMETER: 1,
  EVENT: 2
};

/**
 * @enum {number}
 */
proto.yamcs.protobuf.alarms.AlarmSeverity = {
  WATCH: 1,
  WARNING: 2,
  DISTRESS: 3,
  CRITICAL: 4,
  SEVERE: 5
};

goog.object.extend(exports, proto.yamcs.protobuf.alarms);
